owner: pickyzz # GitHub username
repo: uptime-monitor # GitHub repository name
sites: # List of endpoints to track
  - name: Pickyzz.dev
    url: https://www.pickyzz.dev
assignees: # Users to assign downtime issues (optional)
  - AnandChowdhary
status-website: # Status website (optional)
  cname: status2.pickyzz.dev # Custom domain CNAME
  name: Pickyzz service status # Status website title
